# Generated by Django 5.2.9 on 2025-12-03 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("heat", "Heat Treatment"),
                            ("rough", "Rough"),
                            ("preform", "Preform"),
                            ("cutting", "Cutting"),
                            ("calibrate", "Calibrate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateField(blank=True, null=True)),
                ("artisan", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "gemstone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="inventory.gemstone",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "gemstone__sku"],
                "unique_together": {("gemstone", "stage", "started_at")},
            },
        ),
    ]
