# Generated by Django 5.2.9 on 2025-12-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gemstone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("stone_type", models.CharField(max_length=100)),
                ("weight_carat", models.DecimalField(decimal_places=3, max_digits=10)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("clarity", models.CharField(blank=True, max_length=50)),
                ("shape", models.CharField(blank=True, max_length=50)),
                ("origin", models.CharField(blank=True, max_length=100)),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("production", "In Production"),
                            ("memo", "On Memo"),
                            ("sold", "Sold"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("current_stage", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sku"],
            },
        ),
    ]
